// <auto-generated />
using System;
using Contact_zoo_at_home.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Contact_zoo_at_home.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompanyWorkersInContract", b =>
                {
                    b.Property<int>("ContractsToRepresentId")
                        .HasColumnType("int");

                    b.Property<int>("PetRepresentativesId")
                        .HasColumnType("int");

                    b.HasKey("ContractsToRepresentId", "PetRepresentativesId");

                    b.HasIndex("PetRepresentativesId");

                    b.ToTable("CompanyWorkersInContract");
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Comments.BaseComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Comments", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Contracts.BaseContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityType")
                        .HasColumnType("int");

                    b.Property<string>("ContractAdress")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("ContractDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ContractorId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("StatusOfTheContract")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContractorId");

                    b.HasIndex("CustomerId");

                    b.ToTable("BaseContract");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Notifications.InnerNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NotificationTargetId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NotificationTargetId");

                    b.ToTable("InnerNotifications");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Pets.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityType")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CurrentPetStatus")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("RatedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("RestorationTimeInDays")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SubSpecies")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Users.BaseUser", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FullName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("ProfileImage")
                        .HasMaxLength(1048576)
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("RatedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Users.Special.UnregisteredPetRepresentative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ContractToRepresentId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContractToRepresentId");

                    b.ToTable("CustomRepresentatives", (string)null);
                });

            modelBuilder.Entity("PetsInContractJoin", b =>
                {
                    b.Property<int>("BaseContractId")
                        .HasColumnType("int");

                    b.Property<int>("PetsInContractId")
                        .HasColumnType("int");

                    b.HasKey("BaseContractId", "PetsInContractId");

                    b.HasIndex("PetsInContractId");

                    b.ToTable("PetsInContractJoin");
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Comments.PetComment", b =>
                {
                    b.HasBaseType("Contact_zoo_at_home.Core.Entities.Comments.BaseComment");

                    b.Property<int?>("AnswerToId")
                        .HasColumnType("int");

                    b.Property<int>("CommentTargetId")
                        .HasColumnType("int");

                    b.HasIndex("AnswerToId");

                    b.HasIndex("CommentTargetId");

                    b.ToTable("PetComments");
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Comments.UserComment", b =>
                {
                    b.HasBaseType("Contact_zoo_at_home.Core.Entities.Comments.BaseComment");

                    b.Property<float>("CommentRating")
                        .HasColumnType("real");

                    b.Property<int>("CommentTargetId")
                        .HasColumnType("int");

                    b.HasIndex("CommentTargetId");

                    b.ToTable("UserComments");
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Contracts.StandartContract", b =>
                {
                    b.HasBaseType("Contact_zoo_at_home.Core.Entities.Contracts.BaseContract");

                    b.ToTable("StandartContract");
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Notifications.InnerRatingNotification", b =>
                {
                    b.HasBaseType("Contact_zoo_at_home.Core.Entities.Notifications.InnerNotification");

                    b.Property<int?>("RateTargetPetId")
                        .HasColumnType("int");

                    b.Property<int?>("RateTargetUserId")
                        .HasColumnType("int");

                    b.HasIndex("RateTargetPetId");

                    b.HasIndex("RateTargetUserId");

                    b.ToTable("InnerRatingNotifications");
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Users.BasePetOwner", b =>
                {
                    b.HasBaseType("Contact_zoo_at_home.Core.Entities.Users.BaseUser");

                    b.ToTable("PetOwners", (string)null);
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Users.IndividualUsers.CompanyPetRepresentative", b =>
                {
                    b.HasBaseType("Contact_zoo_at_home.Core.Entities.Users.BaseUser");

                    b.Property<int>("CompanyRepresentedId")
                        .HasColumnType("int");

                    b.HasIndex("CompanyRepresentedId");

                    b.ToTable("CompanyWorkers", (string)null);
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Users.IndividualUsers.CustomerUser", b =>
                {
                    b.HasBaseType("Contact_zoo_at_home.Core.Entities.Users.BaseUser");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Users.IndividualUsers.Company", b =>
                {
                    b.HasBaseType("Contact_zoo_at_home.Core.Entities.Users.BasePetOwner");

                    b.Property<string>("CompanyDescription")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Users.IndividualUsers.IndividualPetOwner", b =>
                {
                    b.HasBaseType("Contact_zoo_at_home.Core.Entities.Users.BasePetOwner");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.ToTable("IndividualPetOwners", (string)null);
                });

            modelBuilder.Entity("CompanyWorkersInContract", b =>
                {
                    b.HasOne("Contact_zoo_at_home.Core.Entities.Contracts.BaseContract", null)
                        .WithMany()
                        .HasForeignKey("ContractsToRepresentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Contact_zoo_at_home.Core.Entities.Users.IndividualUsers.CompanyPetRepresentative", null)
                        .WithMany()
                        .HasForeignKey("PetRepresentativesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Comments.BaseComment", b =>
                {
                    b.HasOne("Contact_zoo_at_home.Core.Entities.Users.BaseUser", "Author")
                        .WithMany("MyComments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Contracts.BaseContract", b =>
                {
                    b.HasOne("Contact_zoo_at_home.Core.Entities.Users.BasePetOwner", "Contractor")
                        .WithMany("ActiveContracts")
                        .HasForeignKey("ContractorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Contact_zoo_at_home.Core.Entities.Users.IndividualUsers.CustomerUser", "Customer")
                        .WithMany("ActiveContracts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Contractor");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Notifications.InnerNotification", b =>
                {
                    b.HasOne("Contact_zoo_at_home.Core.Entities.Users.BaseUser", "NotificationTarget")
                        .WithMany()
                        .HasForeignKey("NotificationTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationTarget");
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Pets.Pet", b =>
                {
                    b.HasOne("Contact_zoo_at_home.Core.Entities.Users.BasePetOwner", "Owner")
                        .WithMany("OwnedPets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Contact_zoo_at_home.Core.Entities.Pets.ExtraPetOption", "PetOptions", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("OptionLanguage")
                                .HasColumnType("int");

                            b1.Property<string>("OptionName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<string>("OptionValue")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<int>("PetId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("PetId");

                            b1.ToTable("PetOptions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PetId");
                        });

                    b.OwnsMany("Contact_zoo_at_home.Core.Entities.Pets.PetBlockedDate", "BlockedDates", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("BlockedDate")
                                .HasColumnType("datetime2");

                            b1.Property<int>("PetId")
                                .HasColumnType("int");

                            b1.Property<int>("Reason")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("PetId");

                            b1.ToTable("PetBlockedDates", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PetId");
                        });

                    b.OwnsMany("Contact_zoo_at_home.Core.Entities.Pets.PetImage", "PetImages", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<byte[]>("Image")
                                .IsRequired()
                                .HasMaxLength(1048576)
                                .HasColumnType("varbinary(max)");

                            b1.Property<string>("ImageName")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<int>("PetId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("PetId");

                            b1.ToTable("PetImages", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PetId");
                        });

                    b.Navigation("BlockedDates");

                    b.Navigation("Owner");

                    b.Navigation("PetImages");

                    b.Navigation("PetOptions");
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Users.BaseUser", b =>
                {
                    b.OwnsOne("Contact_zoo_at_home.Core.Entities.Notifications.NotificationOptions", "NotificationOptions", b1 =>
                        {
                            b1.Property<int>("BaseUserId")
                                .HasColumnType("int");

                            b1.Property<bool>("NotifyOnPhone")
                                .HasColumnType("bit");

                            b1.Property<bool>("NotifyOnTelegram")
                                .HasColumnType("bit");

                            b1.Property<bool>("NotifyOnViber")
                                .HasColumnType("bit");

                            b1.Property<string>("OtherPhones")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BaseUserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("BaseUserId");
                        });

                    b.Navigation("NotificationOptions")
                        .IsRequired();
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Users.Special.UnregisteredPetRepresentative", b =>
                {
                    b.HasOne("Contact_zoo_at_home.Core.Entities.Users.IndividualUsers.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("Contact_zoo_at_home.Core.Entities.Contracts.BaseContract", "ContractToRepresent")
                        .WithMany("UnregisteredPetRepresentatives")
                        .HasForeignKey("ContractToRepresentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("ContractToRepresent");
                });

            modelBuilder.Entity("PetsInContractJoin", b =>
                {
                    b.HasOne("Contact_zoo_at_home.Core.Entities.Contracts.BaseContract", null)
                        .WithMany()
                        .HasForeignKey("BaseContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Contact_zoo_at_home.Core.Entities.Pets.Pet", null)
                        .WithMany()
                        .HasForeignKey("PetsInContractId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Comments.PetComment", b =>
                {
                    b.HasOne("Contact_zoo_at_home.Core.Entities.Comments.PetComment", "AnswerTo")
                        .WithMany()
                        .HasForeignKey("AnswerToId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("Contact_zoo_at_home.Core.Entities.Pets.Pet", "CommentTarget")
                        .WithMany("Comments")
                        .HasForeignKey("CommentTargetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Contact_zoo_at_home.Core.Entities.Comments.BaseComment", null)
                        .WithOne()
                        .HasForeignKey("Contact_zoo_at_home.Core.Entities.Comments.PetComment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnswerTo");

                    b.Navigation("CommentTarget");
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Comments.UserComment", b =>
                {
                    b.HasOne("Contact_zoo_at_home.Core.Entities.Users.BaseUser", "CommentTarget")
                        .WithMany("Comments")
                        .HasForeignKey("CommentTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Contact_zoo_at_home.Core.Entities.Comments.BaseComment", null)
                        .WithOne()
                        .HasForeignKey("Contact_zoo_at_home.Core.Entities.Comments.UserComment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommentTarget");
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Contracts.StandartContract", b =>
                {
                    b.HasOne("Contact_zoo_at_home.Core.Entities.Contracts.BaseContract", null)
                        .WithOne()
                        .HasForeignKey("Contact_zoo_at_home.Core.Entities.Contracts.StandartContract", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Notifications.InnerRatingNotification", b =>
                {
                    b.HasOne("Contact_zoo_at_home.Core.Entities.Notifications.InnerNotification", null)
                        .WithOne()
                        .HasForeignKey("Contact_zoo_at_home.Core.Entities.Notifications.InnerRatingNotification", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Contact_zoo_at_home.Core.Entities.Pets.Pet", "RateTargetPet")
                        .WithMany()
                        .HasForeignKey("RateTargetPetId");

                    b.HasOne("Contact_zoo_at_home.Core.Entities.Users.BaseUser", "RateTargetUser")
                        .WithMany()
                        .HasForeignKey("RateTargetUserId");

                    b.Navigation("RateTargetPet");

                    b.Navigation("RateTargetUser");
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Users.BasePetOwner", b =>
                {
                    b.HasOne("Contact_zoo_at_home.Core.Entities.Users.BaseUser", null)
                        .WithOne()
                        .HasForeignKey("Contact_zoo_at_home.Core.Entities.Users.BasePetOwner", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Users.IndividualUsers.CompanyPetRepresentative", b =>
                {
                    b.HasOne("Contact_zoo_at_home.Core.Entities.Users.IndividualUsers.Company", "CompanyRepresented")
                        .WithMany("CompanyPetRepresentatives")
                        .HasForeignKey("CompanyRepresentedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Contact_zoo_at_home.Core.Entities.Users.BaseUser", null)
                        .WithOne()
                        .HasForeignKey("Contact_zoo_at_home.Core.Entities.Users.IndividualUsers.CompanyPetRepresentative", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyRepresented");
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Users.IndividualUsers.CustomerUser", b =>
                {
                    b.HasOne("Contact_zoo_at_home.Core.Entities.Users.BaseUser", null)
                        .WithOne()
                        .HasForeignKey("Contact_zoo_at_home.Core.Entities.Users.IndividualUsers.CustomerUser", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Users.IndividualUsers.Company", b =>
                {
                    b.HasOne("Contact_zoo_at_home.Core.Entities.Users.BasePetOwner", null)
                        .WithOne()
                        .HasForeignKey("Contact_zoo_at_home.Core.Entities.Users.IndividualUsers.Company", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Users.IndividualUsers.IndividualPetOwner", b =>
                {
                    b.HasOne("Contact_zoo_at_home.Core.Entities.Users.BasePetOwner", null)
                        .WithOne()
                        .HasForeignKey("Contact_zoo_at_home.Core.Entities.Users.IndividualUsers.IndividualPetOwner", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Contracts.BaseContract", b =>
                {
                    b.Navigation("UnregisteredPetRepresentatives");
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Pets.Pet", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Users.BaseUser", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("MyComments");
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Users.BasePetOwner", b =>
                {
                    b.Navigation("ActiveContracts");

                    b.Navigation("OwnedPets");
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Users.IndividualUsers.CustomerUser", b =>
                {
                    b.Navigation("ActiveContracts");
                });

            modelBuilder.Entity("Contact_zoo_at_home.Core.Entities.Users.IndividualUsers.Company", b =>
                {
                    b.Navigation("CompanyPetRepresentatives");
                });
#pragma warning restore 612, 618
        }
    }
}
